version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project
    ports:
      - '5434:5434'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3006:3006'
